spring.application.name=enfermeria-app
spring.datasource.url=jdbc:mysql://localhost:3306/enfermeria_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=IN5AM
spring.datasource.password=_odmon5Am
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true